import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import {
  ShieldCheck,
  Wand2,
  Sparkles,
  ArrowRight,
  CheckCircle2,
  ChevronRight,
  GraduationCap,
  Briefcase,
  BookOpen,
  Newspaper,
  PenTool,
  Check
} from 'lucide-react';
import { runClientNLPAnalysis } from '../utils/nlpAnalysis';
import { humanizerService } from '../services/humanizerService';

export const Home: React.FC = () => {

  // Mini Detector Demo State
  const [detectorInput, setDetectorInput] = useState(
    'The implementation of artificial intelligence systems in clinical healthcare environments demonstrates significant improvements in diagnostic efficiency. Furthermore, it is important to note that automated neural networks play a pivotal role in radiological predictions.'
  );
  const [detectorResult, setDetectorResult] = useState<{
    ai: number;
    human: number;
    confidence: string;
  } | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  // Mini Humanizer Demo State
  const [humanizerInput, setHumanizerInput] = useState(
    'The implementation of the proposed system demonstrates significant improvements in operational efficiency. Furthermore, it is important to note that employees will utilize the dashboard daily.'
  );
  const [humanizerResult, setHumanizerResult] = useState<string | null>(null);
  const [isHumanizing, setIsHumanizing] = useState(false);

  // FAQ Accordion State
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const handleMiniDetect = () => {
    setIsAnalyzing(true);
    setTimeout(() => {
      const res = runClientNLPAnalysis(detectorInput);
      setDetectorResult({
        ai: res.aiProbability,
        human: res.humanProbability,
        confidence: res.confidence
      });
      setIsAnalyzing(false);
    }, 600);
  };

  const handleMiniHumanize = async () => {
    setIsHumanizing(true);
    setTimeout(async () => {
      const res = await humanizerService.humanize({
        text: humanizerInput,
        tone: 'natural',
        strength: 2,
        style: 'clear',
        preserveOptions: {
          meaning: true,
          facts: true,
          citations: true,
          technical: true,
          urls: true,
          numbers: true,
          formatting: true
        }
      });
      setHumanizerResult(res.improvedText);
      setIsHumanizing(false);
    }, 700);
  };

  const faqs = [
    {
      q: 'What is an AI content detector?',
      a: 'An AI content detector analyzes text for statistical regularity, vocabulary repetition, burstiness (sentence length variance), and predictable phrasing commonly generated by large language models.'
    },
    {
      q: 'Is AI detection 100% accurate?',
      a: 'No. AI detection is inherently probabilistic. Detectors can produce both false positives (human writing flagged as AI) and false negatives. Our platform transparently displays confidence estimates and reminds users to treat scores as guidelines rather than definitive proof.'
    },
    {
      q: 'What does the AI Humanizer do?',
      a: 'The humanizer refines robotic phrasing, varies sentence structures, balances sentence cadences, and adapts tone to make writing sound organic and personal—while preserving your original facts, citations, numbers, and core meaning.'
    },
    {
      q: 'Can the humanizer alter my core meaning?',
      a: 'The system strictly prioritizes meaning preservation and fact protection. However, we always encourage writers to review and polish the generated draft to align with their unique personal voice.'
    },
    {
      q: 'Can I upload full documents?',
      a: 'Yes! HumanCheck AI supports direct uploading of .txt and .docx files (up to 5MB) with drag-and-drop capability for fast batch workflow.'
    },
    {
      q: 'Is my content stored or shared?',
      a: 'Your privacy is paramount. You have complete control over your history, with one-click options to rename, export, or permanently purge all analysis data at any time.'
    },
    {
      q: 'Can I use HumanCheck AI on mobile devices?',
      a: 'Yes! The entire platform is built with a responsive interface optimized for desktop, iPad/tablets, Android phones, and iPhones.'
    }
  ];

  const useCases = [
    {
      title: 'Students',
      desc: 'Improve the clarity, flow, and readability of academic essays and coursework.',
      icon: GraduationCap,
      color: 'from-blue-500 to-indigo-600'
    },
    {
      title: 'Researchers',
      desc: 'Review academic papers for stylistic consistency, cadence, and citation integrity.',
      icon: BookOpen,
      color: 'from-purple-500 to-indigo-600'
    },
    {
      title: 'Content Writers',
      desc: 'Transform mechanical drafts into lively, engaging copy with authentic tone.',
      icon: PenTool,
      color: 'from-emerald-500 to-teal-600'
    },
    {
      title: 'Businesses & Teams',
      desc: 'Refine customer communications, memos, and proposals with crisp professional tone.',
      icon: Briefcase,
      color: 'from-amber-500 to-orange-600'
    },
    {
      title: 'Bloggers & Creators',
      desc: 'Create captivating, readable articles that connect genuinely with your audience.',
      icon: Newspaper,
      color: 'from-rose-500 to-pink-600'
    },
    {
      title: 'Educators & Teachers',
      desc: 'Understand linguistic patterns with responsible, probabilistic transparency.',
      icon: ShieldCheck,
      color: 'from-indigo-500 to-brand-600'
    }
  ];

  return (
    <div className="space-y-24 sm:space-y-32 pb-24 overflow-hidden">
      {/* 1. HERO SECTION */}
      <section className="relative pt-12 sm:pt-20 lg:pt-28 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto text-center">
        {/* Subtle Ambient Background Gradients */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] sm:w-[800px] h-[350px] bg-gradient-to-tr from-brand-500/15 via-accent-500/10 to-transparent blur-3xl -z-10 rounded-full pointer-events-none" />

        {/* Badge */}
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-brand-200 dark:border-brand-800/80 bg-brand-50/80 dark:bg-brand-950/60 text-brand-700 dark:text-brand-300 text-xs font-semibold shadow-subtle mb-8 animate-fade-in">
          <Sparkles className="w-3.5 h-3.5 text-brand-600 dark:text-brand-400" />
          <span>Next-Gen Writing Intelligence • Detector + Humanizer</span>
        </div>

        {/* Hero Heading */}
        <h1 className="text-4xl sm:text-6xl lg:text-7xl font-extrabold tracking-tight text-slate-900 dark:text-white max-w-5xl mx-auto leading-[1.12]">
          Detect AI.{' '}
          <span className="bg-gradient-to-r from-brand-600 via-indigo-500 to-accent-600 bg-clip-text text-transparent">
            Improve your writing.
          </span>{' '}
          Sound like yourself.
        </h1>

        {/* Hero Subtitle */}
        <p className="mt-6 text-base sm:text-xl text-slate-600 dark:text-slate-300 max-w-3xl mx-auto leading-relaxed font-normal">
          Analyze writing patterns and refine your text with an easy-to-use AI detector and writing humanizer built for students, creators, researchers, and professionals.
        </p>

        {/* Hero CTA Buttons */}
        <div className="mt-9 flex flex-col sm:flex-row items-center justify-center gap-4 max-w-md mx-auto">
          <Link
            to="/detector"
            className="w-full sm:w-auto px-7 py-3.5 rounded-2xl text-base font-bold bg-gradient-to-r from-brand-600 to-indigo-600 hover:from-brand-700 hover:to-indigo-700 text-white shadow-lg hover:shadow-glow transition-all flex items-center justify-center gap-2 transform active:scale-95"
          >
            <ShieldCheck className="w-5 h-5" />
            Check My Text
          </Link>
          <Link
            to="/humanizer"
            className="w-full sm:w-auto px-7 py-3.5 rounded-2xl text-base font-bold border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-100 hover:bg-slate-50 dark:hover:bg-slate-800 transition-all flex items-center justify-center gap-2 shadow-subtle transform active:scale-95"
          >
            <Wand2 className="w-5 h-5 text-brand-600 dark:text-brand-400" />
            Humanize Writing
          </Link>
        </div>

        {/* Trust Statement */}
        <p className="mt-6 text-xs text-slate-400 dark:text-slate-500 max-w-lg mx-auto leading-normal">
          “AI detection is probabilistic and should be treated as an assessment, not definitive proof of authorship.”
        </p>
      </section>

      {/* 2. INTERACTIVE DEMO SHOWCASE SECTION */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Mini AI Detector Demo */}
          <div className="p-6 sm:p-8 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-premium flex flex-col justify-between space-y-6">
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div className="p-2 rounded-xl bg-brand-50 dark:bg-brand-950 text-brand-600 dark:text-brand-400">
                    <ShieldCheck className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="text-lg font-bold text-slate-900 dark:text-white">
                      Try the AI Detector
                    </h3>
                    <p className="text-xs text-slate-500">
                      Paste a paragraph to see sample pattern extraction
                    </p>
                  </div>
                </div>
                <span className="text-[10px] font-bold uppercase tracking-wider bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 px-2 py-1 rounded">
                  Live Preview
                </span>
              </div>

              <textarea
                rows={4}
                value={detectorInput}
                onChange={(e) => setDetectorInput(e.target.value)}
                placeholder="Paste a paragraph here to see an example analysis."
                className="w-full p-3.5 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50/70 dark:bg-slate-800/60 text-xs leading-relaxed text-slate-800 dark:text-slate-100 focus:outline-none focus:ring-2 focus:ring-brand-500 resize-none"
              />

              <div className="flex items-center justify-between">
                <button
                  type="button"
                  onClick={handleMiniDetect}
                  disabled={isAnalyzing || !detectorInput.trim()}
                  className="px-5 py-2.5 rounded-xl text-xs font-bold bg-brand-600 hover:bg-brand-700 text-white shadow transition-all disabled:opacity-50"
                >
                  {isAnalyzing ? 'Analyzing...' : 'Analyze Pattern'}
                </button>
                <Link
                  to="/detector"
                  className="text-xs font-semibold text-brand-600 dark:text-brand-400 hover:underline flex items-center gap-1"
                >
                  Open Full Detector <ArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            </div>

            {/* Results Display */}
            {detectorResult && (
              <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 space-y-3 animate-fade-in">
                <div className="flex items-center justify-between text-xs">
                  <span className="text-slate-500 font-medium">Estimated AI Likelihood:</span>
                  <span className={`font-extrabold ${detectorResult.ai > 60 ? 'text-rose-600' : 'text-emerald-600'}`}>
                    {detectorResult.ai}%
                  </span>
                </div>
                <div className="flex items-center justify-between text-xs">
                  <span className="text-slate-500 font-medium">Human Likelihood:</span>
                  <span className="font-bold text-emerald-600">{detectorResult.human}%</span>
                </div>
                <div className="flex items-center justify-between text-xs">
                  <span className="text-slate-500 font-medium">Assessment Confidence:</span>
                  <span className="font-bold uppercase text-brand-600">{detectorResult.confidence}</span>
                </div>
                <div className="w-full bg-slate-200 dark:bg-slate-700 h-2 rounded-full overflow-hidden">
                  <div
                    className="bg-brand-600 h-full rounded-full transition-all duration-500"
                    style={{ width: `${detectorResult.ai}%` }}
                  />
                </div>
              </div>
            )}
          </div>

          {/* Mini Humanizer Demo */}
          <div className="p-6 sm:p-8 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-premium flex flex-col justify-between space-y-6">
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div className="p-2 rounded-xl bg-accent-50 dark:bg-purple-950 text-accent-600 dark:text-accent-400">
                    <Wand2 className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="text-lg font-bold text-slate-900 dark:text-white">
                      Try the Humanizer
                    </h3>
                    <p className="text-xs text-slate-500">
                      Transform stiff expressions into fluid conversational flow
                    </p>
                  </div>
                </div>
                <span className="text-[10px] font-bold uppercase tracking-wider bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 px-2 py-1 rounded">
                  Live Preview
                </span>
              </div>

              <textarea
                rows={4}
                value={humanizerInput}
                onChange={(e) => setHumanizerInput(e.target.value)}
                placeholder="Paste AI or formal draft to humanize..."
                className="w-full p-3.5 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50/70 dark:bg-slate-800/60 text-xs leading-relaxed text-slate-800 dark:text-slate-100 focus:outline-none focus:ring-2 focus:ring-brand-500 resize-none"
              />

              <div className="flex items-center justify-between">
                <button
                  type="button"
                  onClick={handleMiniHumanize}
                  disabled={isHumanizing || !humanizerInput.trim()}
                  className="px-5 py-2.5 rounded-xl text-xs font-bold bg-gradient-to-r from-accent-600 to-indigo-600 hover:from-accent-700 hover:to-indigo-700 text-white shadow transition-all disabled:opacity-50"
                >
                  {isHumanizing ? 'Improving Flow...' : 'Improve Writing'}
                </button>
                <Link
                  to="/humanizer"
                  className="text-xs font-semibold text-accent-600 dark:text-accent-400 hover:underline flex items-center gap-1"
                >
                  Open Full Humanizer <ArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            </div>

            {/* Results Display */}
            {humanizerResult && (
              <div className="p-4 rounded-2xl bg-emerald-50/70 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-800/60 space-y-2 animate-fade-in">
                <span className="text-[11px] font-bold uppercase tracking-wider text-emerald-800 dark:text-emerald-300 block">
                  Rewritten Sample
                </span>
                <p className="text-xs text-slate-800 dark:text-slate-200 leading-relaxed italic">
                  "{humanizerResult}"
                </p>
                <div className="flex items-center gap-1 text-[11px] font-semibold text-emerald-700 dark:text-emerald-400 pt-1">
                  <CheckCircle2 className="w-3.5 h-3.5" />
                  Readability enhanced & cliches eliminated
                </div>
              </div>
            )}
          </div>
        </div>
      </section>

      {/* 3. HOW IT WORKS (3-STEP) */}
      <section id="how-it-works" className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center space-y-12">
        <div className="space-y-3">
          <h2 className="text-xs font-bold uppercase tracking-widest text-brand-600 dark:text-brand-400">
            Intuitive Workflow
          </h2>
          <h3 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white">
            How HumanCheck AI Works
          </h3>
          <p className="text-sm sm:text-base text-slate-600 dark:text-slate-400 max-w-xl mx-auto">
            Three simple steps to assess predictability and elevate your personal voice.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-left">
          {[
            {
              step: '01',
              title: 'Paste Your Text',
              desc: 'Add your writing, paste an article draft, or upload a TXT/DOCX document directly into the editor.'
            },
            {
              step: '02',
              title: 'Analyze or Improve',
              desc: 'Run the pattern detector for statistical signals or tune the humanizer sliders to match your preferred tone and strength.'
            },
            {
              step: '03',
              title: 'Review the Result',
              desc: 'Inspect sentence-level observations, compare diff highlights, and export polished reports or clean copy.'
            }
          ].map((item, idx) => (
            <div
              key={idx}
              className="p-8 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-subtle hover:shadow-premium transition-all space-y-4 relative group"
            >
              <span className="text-3xl font-black text-brand-600/30 dark:text-brand-400/20 group-hover:text-brand-600 transition-colors">
                {item.step}
              </span>
              <h4 className="text-lg font-bold text-slate-900 dark:text-white">
                {item.title}
              </h4>
              <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                {item.desc}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* 4. USE CASES SECTION */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
        <div className="text-center space-y-3">
          <h2 className="text-xs font-bold uppercase tracking-widest text-brand-600 dark:text-brand-400">
            Tailored For Everyone
          </h2>
          <h3 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white">
            Built For Modern Writers Across Every Field
          </h3>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {useCases.map((uc, idx) => {
            const Icon = uc.icon;
            return (
              <div
                key={idx}
                className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-subtle hover:border-brand-300 dark:hover:border-brand-700 transition-all space-y-3"
              >
                <div className={`w-10 h-10 rounded-xl bg-gradient-to-tr ${uc.color} flex items-center justify-center text-white shadow-sm`}>
                  <Icon className="w-5 h-5" />
                </div>
                <h4 className="text-base font-bold text-slate-900 dark:text-white">
                  {uc.title}
                </h4>
                <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
                  {uc.desc}
                </p>
              </div>
            );
          })}
        </div>
      </section>

      {/* 5. PRICING PREVIEW */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center space-y-12">
        <div className="space-y-3">
          <h2 className="text-xs font-bold uppercase tracking-widest text-brand-600 dark:text-brand-400">
            Transparent Pricing
          </h2>
          <h3 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white">
            Simple, Accessible Plans
          </h3>
          <p className="text-sm text-slate-600 dark:text-slate-400">
            Start free, upgrade as your writing demands grow.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto text-left">
          {/* Free Plan */}
          <div className="p-8 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-subtle flex flex-col justify-between space-y-6">
            <div className="space-y-4">
              <h4 className="text-lg font-bold text-slate-900 dark:text-white">Free</h4>
              <div className="text-3xl font-extrabold text-slate-900 dark:text-white">
                ₹0 <span className="text-sm font-normal text-slate-500">/ month</span>
              </div>
              <ul className="space-y-2.5 text-xs text-slate-600 dark:text-slate-300">
                <li className="flex items-center gap-2">
                  <Check className="w-4 h-4 text-emerald-500" /> 5 analyses per day
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-4 h-4 text-emerald-500" /> Basic detector & humanizer
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-4 h-4 text-emerald-500" /> 500 words per request
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-4 h-4 text-emerald-500" /> History saved for 7 days
                </li>
              </ul>
            </div>
            <Link
              to="/detector"
              className="w-full py-2.5 text-center rounded-xl text-xs font-bold border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-900 dark:text-white transition-all"
            >
              Get Started Free
            </Link>
          </div>

          {/* Pro Plan */}
          <div className="p-8 rounded-3xl bg-white dark:bg-slate-900 border-2 border-brand-500 shadow-glow flex flex-col justify-between space-y-6 relative">
            <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-brand-600 text-white px-3 py-0.5 rounded-full text-[10px] font-extrabold uppercase tracking-wider">
              Most Popular
            </div>
            <div className="space-y-4">
              <h4 className="text-lg font-bold text-slate-900 dark:text-white">Pro</h4>
              <div className="text-3xl font-extrabold text-slate-900 dark:text-white">
                ₹299 <span className="text-sm font-normal text-slate-500">/ month</span>
              </div>
              <ul className="space-y-2.5 text-xs text-slate-600 dark:text-slate-300">
                <li className="flex items-center gap-2">
                  <Check className="w-4 h-4 text-emerald-500" /> 100 analyses per month
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-4 h-4 text-emerald-500" /> Advanced sentence inspection
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-4 h-4 text-emerald-500" /> 5,000 words per request
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-4 h-4 text-emerald-500" /> Unlimited document history
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-4 h-4 text-emerald-500" /> Formatted PDF & TXT reports
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-4 h-4 text-emerald-500" /> Multiple writing tones & styles
                </li>
              </ul>
            </div>
            <Link
              to="/pricing"
              className="w-full py-2.5 text-center rounded-xl text-xs font-bold bg-brand-600 hover:bg-brand-700 text-white shadow transition-all"
            >
              Start Pro Plan
            </Link>
          </div>

          {/* Professional Plan */}
          <div className="p-8 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-subflex flex flex-col justify-between space-y-6">
            <div className="space-y-4">
              <h4 className="text-lg font-bold text-slate-900 dark:text-white">Professional</h4>
              <div className="text-3xl font-extrabold text-slate-900 dark:text-white">
                ₹799 <span className="text-sm font-normal text-slate-500">/ month</span>
              </div>
              <ul className="space-y-2.5 text-xs text-slate-600 dark:text-slate-300">
                <li className="flex items-center gap-2">
                  <Check className="w-4 h-4 text-emerald-500" /> Unlimited analyses & humanizations
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-4 h-4 text-emerald-500" /> 10,000 words per request
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-4 h-4 text-emerald-500" /> Priority processing speed
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-4 h-4 text-emerald-500" /> Advanced writing & tone presets
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-4 h-4 text-emerald-500" /> Team workspaces & API access
                </li>
              </ul>
            </div>
            <Link
              to="/pricing"
              className="w-full py-2.5 text-center rounded-xl text-xs font-bold border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-900 dark:text-white transition-all"
            >
              Choose Professional
            </Link>
          </div>
        </div>
      </section>

      {/* 6. FAQ ACCORDION SECTION */}
      <section id="faq" className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
        <div className="text-center space-y-3">
          <h2 className="text-xs font-bold uppercase tracking-widest text-brand-600 dark:text-brand-400">
            Got Questions?
          </h2>
          <h3 className="text-3xl font-extrabold text-slate-900 dark:text-white">
            Frequently Asked Questions
          </h3>
        </div>

        <div className="space-y-3">
          {faqs.map((faq, idx) => (
            <div
              key={idx}
              className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 overflow-hidden transition-all shadow-subtle"
            >
              <button
                type="button"
                onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                className="w-full p-5 text-left flex items-center justify-between gap-4 font-bold text-sm text-slate-900 dark:text-white"
              >
                <span>{faq.q}</span>
                <ChevronRight
                  className={`w-4 h-4 text-slate-400 transition-transform ${
                    openFaq === idx ? 'rotate-90 text-brand-600' : ''
                  }`}
                />
              </button>
              {openFaq === idx && (
                <div className="px-5 pb-5 text-xs text-slate-600 dark:text-slate-400 leading-relaxed border-t border-slate-100 dark:border-slate-800 pt-3">
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* 7. FINAL CTA BANNER */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="p-8 sm:p-14 rounded-3xl bg-gradient-to-tr from-brand-600 via-indigo-600 to-accent-600 text-white shadow-glow text-center space-y-6 relative overflow-hidden">
          <div className="relative z-10 max-w-2xl mx-auto space-y-4">
            <h3 className="text-3xl sm:text-4xl font-black">
              Ready to refine your writing?
            </h3>
            <p className="text-sm sm:text-base text-brand-100 leading-relaxed">
              Join thousands of students, researchers, and professional writers crafting clear, authentic text every day.
            </p>
            <div className="pt-2 flex flex-col sm:flex-row items-center justify-center gap-3">
              <Link
                to="/register"
                className="px-8 py-3.5 rounded-2xl bg-white text-slate-900 font-bold text-sm shadow hover:bg-brand-50 transition-all"
              >
                Get Started Free
              </Link>
              <Link
                to="/detector"
                className="px-8 py-3.5 rounded-2xl bg-brand-700/60 hover:bg-brand-700 text-white font-bold text-sm border border-brand-400/40 transition-all"
              >
                Try Online Detector
              </Link>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};
